--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/r3pt1s/BetterForms
build-by-default: true
branches:
- main
projects:
  BetterForms:
    path: ""
    model: virion
    type: library
...
